spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod :
        - common
---

spring:
  config:
    activate:
      on-profile: common
    import: optional:file:.env[.properties]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    ttl:
      refresh_token: 1209600000
  jwt:
    secret: ${JWT_KEY}
    token:
      access-expiration-time: 43200000   # 12hour
      refresh-expiration-time: 604800000 # 7day


logging:
  config:
    activate:
      on-profile: common
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: DEBUG
        sql: DEBUG

oauth2:
  config:
    activate:
      on-profile: common
  kakao:
    infoUrl: https://kapi.kakao.com

---